2023-03-07T02:00:13.5048939Z ##[group]Run actions/setup-python@v4
2023-03-07T02:00:13.5049232Z with:
2023-03-07T02:00:13.5049510Z   python-version: 3.8
2023-03-07T02:00:13.5049868Z   architecture: x64
2023-03-07T02:00:13.5050150Z   cache: pip
2023-03-07T02:00:13.5050394Z   check-latest: false
2023-03-07T02:00:13.5050893Z   token: ***
2023-03-07T02:00:13.5051189Z   update-environment: true
2023-03-07T02:00:13.5051514Z ##[endgroup]
2023-03-07T02:00:13.6730076Z ##[group]Installed versions
2023-03-07T02:00:13.6848451Z Successfully set up CPython (3.8.16)
2023-03-07T02:00:13.6851542Z ##[endgroup]
2023-03-07T02:00:14.1442933Z [command]/opt/hostedtoolcache/Python/3.8.16/x64/bin/pip cache dir
2023-03-07T02:00:14.5143879Z /home/runner/.cache/pip
2023-03-07T02:00:15.0141671Z Received 6243437 of 6243437 (100.0%), 30.5 MBs/sec
2023-03-07T02:00:15.0142824Z Cache Size: ~6 MB (6243437 B)
2023-03-07T02:00:15.0162797Z [command]/usr/bin/tar -z -xf /home/runner/work/_temp/84ec4f05-f897-4b12-89a7-2d02312d10aa/cache.tgz -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A
2023-03-07T02:00:15.0750605Z Cache restored successfully
2023-03-07T02:00:15.0752293Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.16-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
