2023-03-13T01:45:35.6264075Z ##[group]Run actions/setup-python@v4
2023-03-13T01:45:35.6264315Z with:
2023-03-13T01:45:35.6264518Z   python-version: 3.8
2023-03-13T01:45:35.6264721Z   architecture: x64
2023-03-13T01:45:35.6264915Z   cache: pip
2023-03-13T01:45:35.6265117Z   check-latest: false
2023-03-13T01:45:35.6265477Z   token: ***
2023-03-13T01:45:35.6265679Z   update-environment: true
2023-03-13T01:45:35.6265891Z ##[endgroup]
2023-03-13T01:45:35.7958989Z ##[group]Installed versions
2023-03-13T01:45:35.8093288Z Successfully set up CPython (3.8.16)
2023-03-13T01:45:35.8096934Z ##[endgroup]
2023-03-13T01:45:36.2519370Z [command]/opt/hostedtoolcache/Python/3.8.16/x64/bin/pip cache dir
2023-03-13T01:45:36.6132763Z /home/runner/.cache/pip
2023-03-13T01:45:37.3987704Z Received 6243437 of 6243437 (100.0%), 14.7 MBs/sec
2023-03-13T01:45:37.3988356Z Cache Size: ~6 MB (6243437 B)
2023-03-13T01:45:37.4009130Z [command]/usr/bin/tar -z -xf /home/runner/work/_temp/9f0e2fe3-0c46-4f9c-b13c-7f9e6e4237de/cache.tgz -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A
2023-03-13T01:45:37.4614145Z Cache restored successfully
2023-03-13T01:45:37.4628991Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.16-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
